In [57]:
# Sorting a list
import numpy as np
list1 = [10, 3, 5, 199, 250]
np.sort(list1)

array([  3,   5,  10, 199, 250])

### Scalar: 
Single value Ex: 1, 2, etc

### Vector:
Represented as single dimensional array. Ex: [1,2]

### Matrix:
Multi-dimensional array. 
Ex: 
[
    [1,2],
    [3,4],
    [5,6],
]

# Scalar Functions

In [58]:
# Random integer <n
np.random.randint(17)

15

In [56]:
# Random numbers
np.random.randn()

-0.6179798650058408

# Single Dimensional Array (Vector)

In [25]:
# Create an array from a python list
dnpvector1 = np.array([1,2,3,4,5])
dnpvector1

array([1, 2, 3, 4, 5])

In [26]:
# Create from a python list as a variable
list1 = [10, 11, 12, 13, 14, 15]
dnpvector2 = np.array(list1)
dnpvector2

array([10, 11, 12, 13, 14, 15])

In [27]:
# Convert Array to list
dnpvector2.tolist()
list(dnpvector2)

[10, 11, 12, 13, 14, 15]

In [28]:
# Append element to end of an array
dnpvector1 = np.append(dnpvector1, 100)
dnpvector1

array([  1,   2,   3,   4,   5, 100])

In [32]:
# Append element at index position of an array
dnpvector1 = np.insert(dnpvector1, 3, 10) # 10 is added at index 3 which is 4th position
dnpvector1

array([  1,   2,   3,  10,   4,   5, 100])

In [35]:
# Sort an array
dnpvector1 = np.sort(dnpvector1)
dnpvector1

array([  1,   2,   3,   4,   5,  10, 100])

In [36]:
# Delete value at a certain index 
dnpvector1 = np.delete(dnpvector1, 1) # Element at index 1 gone
dnpvector1

array([  1,   3,   4,   5,  10, 100])

In [39]:
# Concatenate 2 arrays
dnpvector3 = [101, 102, 103]
dnpvector4 = np.concatenate((dnpvector1, dnpvector3), axis=0)
dnpvector4

array([  1,   3,   4,   5,  10, 100, 101, 102, 103])

In [40]:
# Find index of an element in a vector
np.where(dnpvector4==101) # vector name==<value>

(array([6]),)

In [42]:
# Create an array with range
dnp1 = np.arange(1,10,2)
dnp1

array([1, 3, 5, 7, 9])

In [43]:
# Array with n 0s
dnpzero = np.zeros(10) 
dnpzero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
# Array with n 1s
dnpones = np.ones(10) 
dnpones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
# Line Space Function to get equally distant numbers
dnplinespc = np.linspace(1,5,20) # 20 numbers between 1 and 5 equally spaced
dnplinespc

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [46]:
# Max value in an array
dnplinespc.max()

5.0

In [47]:
dnplinespc.min()

1.0

In [48]:
# Index of max or min value
dnplinespc.argmax()

19

In [49]:
dnplinespc.argmin()

0

In [51]:
# Size of an array
dnplinespc.size

20

In [52]:
# Value at a specific index
dnplinespc[5]

2.052631578947368

In [53]:
# VAlue for range of index
dnplinespc[1:5]

array([1.21052632, 1.42105263, 1.63157895, 1.84210526])

# Multi Dimensional Array (Matrix)

In [60]:
# Random numbers: rows, columns
dnprandom = np.random.rand(5,4)
dnprandom

# Rows are axis= 0| Columns are axis = 1 

array([[0.11429338, 0.33513159, 0.23064389, 0.07117711],
       [0.58197489, 0.946771  , 0.85118382, 0.71828621],
       [0.43978564, 0.46637578, 0.73733617, 0.29242979],
       [0.60677327, 0.27990864, 0.74205412, 0.85905447],
       [0.70421353, 0.0283745 , 0.08976707, 0.98547616]])

In [62]:
# Access element in a matrix --> row, column
dnprandom[2,1]
dnprandom[2][1]

0.46637577767623606

In [63]:
# Access a range of elements Subset of multi-dim array
dnprandom[1:3, 2:4]

array([[0.85118382, 0.71828621],
       [0.73733617, 0.29242979]])

In [64]:
# Size of array
dnprandom.shape

(5, 4)

In [65]:
# Data Type
dnprandom.dtype

dtype('float64')

# Operations on Arrays

In [67]:
dnpintmat = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
dnpintmat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [68]:
# Total of all values
dnpintmat.sum()

120

In [69]:
# Values >n
dnpintmat>7

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [71]:
# Create array with values >n
dnpintmat2 = [(dnpintmat>7)]

[array([[False, False, False],
        [False, False, False],
        [False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])]

In [72]:
dnpintmat[dnpintmat2] # Gives an array with all values >n

<ipython-input-72-7f236a946b73>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dnpintmat[dnpintmat2]


array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
# Reassign values in a matrix to a constant
dnpintmat[3, 0:3] = 100
dnpintmat

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 100, 100],
       [ 13,  14,  15]])

In [74]:
# Add 50 to all the values
dnpintmat = dnpintmat + 50
dnpintmat

array([[ 51,  52,  53],
       [ 54,  55,  56],
       [ 57,  58,  59],
       [150, 150, 150],
       [ 63,  64,  65]])

# Statistical Functions

In [76]:
# Standard Deviation
np.std(dnpintmat)

37.31880669760668

In [77]:
# Sq Root of each value
np.sqrt(dnpintmat)

array([[ 7.14142843,  7.21110255,  7.28010989],
       [ 7.34846923,  7.41619849,  7.48331477],
       [ 7.54983444,  7.61577311,  7.68114575],
       [12.24744871, 12.24744871, 12.24744871],
       [ 7.93725393,  8.        ,  8.06225775]])

In [78]:
# Log
np.log(dnpintmat)

array([[3.93182563, 3.95124372, 3.97029191],
       [3.98898405, 4.00733319, 4.02535169],
       [4.04305127, 4.06044301, 4.07753744],
       [5.01063529, 5.01063529, 5.01063529],
       [4.14313473, 4.15888308, 4.17438727]])